#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_dialog.ui'
#
# Created: Mon Jun 13 02:31:42 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_config_dialog(object):
    def setupUi(self, config_dialog):
        config_dialog.setObjectName(_fromUtf8("config_dialog"))
        config_dialog.resize(431, 393)
        self.gridLayout = QtGui.QGridLayout(config_dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_3 = QtGui.QGroupBox(config_dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_6.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_6.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_6.addWidget(self.label_12)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.chainComboBox = QtGui.QComboBox(self.groupBox_3)
        self.chainComboBox.setObjectName(_fromUtf8("chainComboBox"))
        self.chainComboBox.addItem(_fromUtf8(""))
        self.chainComboBox.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.chainComboBox)
        self.channameLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.channameLineEdit.setObjectName(_fromUtf8("channameLineEdit"))
        self.verticalLayout_5.addWidget(self.channameLineEdit)
        self.feeDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.feeDoubleSpinBox.setDecimals(8)
        self.feeDoubleSpinBox.setSingleStep(1e-06)
        self.feeDoubleSpinBox.setObjectName(_fromUtf8("feeDoubleSpinBox"))
        self.verticalLayout_5.addWidget(self.feeDoubleSpinBox)
        self.minconfSpinBox = QtGui.QSpinBox(self.groupBox_3)
        self.minconfSpinBox.setObjectName(_fromUtf8("minconfSpinBox"))
        self.verticalLayout_5.addWidget(self.minconfSpinBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox = QtGui.QGroupBox(config_dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btcuserLineEdit = QtGui.QLineEdit(self.groupBox)
        self.btcuserLineEdit.setObjectName(_fromUtf8("btcuserLineEdit"))
        self.verticalLayout_2.addWidget(self.btcuserLineEdit)
        self.btcpswdLineEdit = QtGui.QLineEdit(self.groupBox)
        self.btcpswdLineEdit.setObjectName(_fromUtf8("btcpswdLineEdit"))
        self.verticalLayout_2.addWidget(self.btcpswdLineEdit)
        self.btchostLineEdit = QtGui.QLineEdit(self.groupBox)
        self.btchostLineEdit.setObjectName(_fromUtf8("btchostLineEdit"))
        self.verticalLayout_2.addWidget(self.btchostLineEdit)
        self.btcportSpinBox = QtGui.QSpinBox(self.groupBox)
        self.btcportSpinBox.setMaximum(99999)
        self.btcportSpinBox.setObjectName(_fromUtf8("btcportSpinBox"))
        self.verticalLayout_2.addWidget(self.btcportSpinBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(config_dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.bmuserLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.bmuserLineEdit.setObjectName(_fromUtf8("bmuserLineEdit"))
        self.verticalLayout_4.addWidget(self.bmuserLineEdit)
        self.bmpswdLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.bmpswdLineEdit.setObjectName(_fromUtf8("bmpswdLineEdit"))
        self.verticalLayout_4.addWidget(self.bmpswdLineEdit)
        self.bmhostLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.bmhostLineEdit.setObjectName(_fromUtf8("bmhostLineEdit"))
        self.verticalLayout_4.addWidget(self.bmhostLineEdit)
        self.bmportSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.bmportSpinBox.setMaximum(99999)
        self.bmportSpinBox.setObjectName(_fromUtf8("bmportSpinBox"))
        self.verticalLayout_4.addWidget(self.bmportSpinBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(config_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.label_9.setBuddy(self.chainComboBox)
        self.label_10.setBuddy(self.channameLineEdit)
        self.label_11.setBuddy(self.feeDoubleSpinBox)
        self.label_12.setBuddy(self.minconfSpinBox)
        self.label.setBuddy(self.btcuserLineEdit)
        self.label_2.setBuddy(self.btcpswdLineEdit)
        self.label_3.setBuddy(self.btchostLineEdit)
        self.label_4.setBuddy(self.btcportSpinBox)
        self.label_5.setBuddy(self.bmuserLineEdit)
        self.label_6.setBuddy(self.bmpswdLineEdit)
        self.label_7.setBuddy(self.bmhostLineEdit)
        self.label_8.setBuddy(self.bmportSpinBox)

        self.retranslateUi(config_dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), config_dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), config_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(config_dialog)
        config_dialog.setTabOrder(self.chainComboBox, self.channameLineEdit)
        config_dialog.setTabOrder(self.channameLineEdit, self.feeDoubleSpinBox)
        config_dialog.setTabOrder(self.feeDoubleSpinBox, self.minconfSpinBox)
        config_dialog.setTabOrder(self.minconfSpinBox, self.btcuserLineEdit)
        config_dialog.setTabOrder(self.btcuserLineEdit, self.btcpswdLineEdit)
        config_dialog.setTabOrder(self.btcpswdLineEdit, self.btchostLineEdit)
        config_dialog.setTabOrder(self.btchostLineEdit, self.btcportSpinBox)
        config_dialog.setTabOrder(self.btcportSpinBox, self.bmuserLineEdit)
        config_dialog.setTabOrder(self.bmuserLineEdit, self.bmpswdLineEdit)
        config_dialog.setTabOrder(self.bmpswdLineEdit, self.bmhostLineEdit)
        config_dialog.setTabOrder(self.bmhostLineEdit, self.bmportSpinBox)
        config_dialog.setTabOrder(self.bmportSpinBox, self.buttonBox)

    def retranslateUi(self, config_dialog):
        config_dialog.setWindowTitle(_translate("config_dialog", "METAbuyer-Qt Settings", None))
        self.groupBox_3.setTitle(_translate("config_dialog", "Configuration:", None))
        self.label_9.setText(_translate("config_dialog", "Bitcoin Chain", None))
        self.label_10.setText(_translate("config_dialog", "Channel", None))
        self.label_11.setText(_translate("config_dialog", "Default Fee", None))
        self.label_12.setText(_translate("config_dialog", "Minimum Confirms", None))
        self.chainComboBox.setItemText(0, _translate("config_dialog", "mainnet", None))
        self.chainComboBox.setItemText(1, _translate("config_dialog", "testnet", None))
        self.groupBox.setTitle(_translate("config_dialog", "Bitcoin Core RPC:", None))
        self.label.setText(_translate("config_dialog", "User", None))
        self.label_2.setText(_translate("config_dialog", "Password", None))
        self.label_3.setText(_translate("config_dialog", "Host", None))
        self.label_4.setText(_translate("config_dialog", "Port", None))
        self.groupBox_2.setTitle(_translate("config_dialog", "Bitmessage RPC:", None))
        self.label_5.setText(_translate("config_dialog", "User", None))
        self.label_6.setText(_translate("config_dialog", "Password", None))
        self.label_7.setText(_translate("config_dialog", "Host", None))
        self.label_8.setText(_translate("config_dialog", "Port", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    config_dialog = QtGui.QDialog()
    ui = Ui_config_dialog()
    ui.setupUi(config_dialog)
    config_dialog.show()
    sys.exit(app.exec_())

