#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metamarket_qt.ui'
#
# Created: Sun May 15 23:32:54 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 557)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.chanTab = QtGui.QWidget()
        self.chanTab.setObjectName(_fromUtf8("chanTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.chanTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.chanGroupBox = QtGui.QGroupBox(self.chanTab)
        self.chanGroupBox.setObjectName(_fromUtf8("chanGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.chanGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chanTableWidget = QtGui.QTableWidget(self.chanGroupBox)
        self.chanTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.chanTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.chanTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.chanTableWidget.setObjectName(_fromUtf8("chanTableWidget"))
        self.chanTableWidget.setColumnCount(2)
        self.chanTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.chanTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.chanTableWidget.setHorizontalHeaderItem(1, item)
        self.chanTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.chanTableWidget.horizontalHeader().setStretchLastSection(True)
        self.chanTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.chanTableWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chanSendButton = QtGui.QPushButton(self.chanGroupBox)
        self.chanSendButton.setObjectName(_fromUtf8("chanSendButton"))
        self.horizontalLayout.addWidget(self.chanSendButton)
        self.chanViewButton = QtGui.QPushButton(self.chanGroupBox)
        self.chanViewButton.setObjectName(_fromUtf8("chanViewButton"))
        self.horizontalLayout.addWidget(self.chanViewButton)
        self.chanDeleteButton = QtGui.QPushButton(self.chanGroupBox)
        self.chanDeleteButton.setObjectName(_fromUtf8("chanDeleteButton"))
        self.horizontalLayout.addWidget(self.chanDeleteButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.chanGroupBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.chanTab, _fromUtf8(""))
        self.marketTab = QtGui.QWidget()
        self.marketTab.setObjectName(_fromUtf8("marketTab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.marketTab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.marketGroupBox = QtGui.QGroupBox(self.marketTab)
        self.marketGroupBox.setObjectName(_fromUtf8("marketGroupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.marketGroupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.marketTableWidget = QtGui.QTableWidget(self.marketGroupBox)
        self.marketTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.marketTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.marketTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.marketTableWidget.setObjectName(_fromUtf8("marketTableWidget"))
        self.marketTableWidget.setColumnCount(2)
        self.marketTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.marketTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.marketTableWidget.setHorizontalHeaderItem(1, item)
        self.marketTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.marketTableWidget.horizontalHeader().setStretchLastSection(True)
        self.marketTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.marketTableWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.marketImportButton = QtGui.QPushButton(self.marketGroupBox)
        self.marketImportButton.setObjectName(_fromUtf8("marketImportButton"))
        self.horizontalLayout_3.addWidget(self.marketImportButton)
        self.marketViewButton = QtGui.QPushButton(self.marketGroupBox)
        self.marketViewButton.setObjectName(_fromUtf8("marketViewButton"))
        self.horizontalLayout_3.addWidget(self.marketViewButton)
        self.marketDeleteButton = QtGui.QPushButton(self.marketGroupBox)
        self.marketDeleteButton.setObjectName(_fromUtf8("marketDeleteButton"))
        self.horizontalLayout_3.addWidget(self.marketDeleteButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.marketGroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.marketTab, _fromUtf8(""))
        self.offerTab = QtGui.QWidget()
        self.offerTab.setObjectName(_fromUtf8("offerTab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.offerTab)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.offerGroupBox = QtGui.QGroupBox(self.offerTab)
        self.offerGroupBox.setObjectName(_fromUtf8("offerGroupBox"))
        self.gridLayout_11 = QtGui.QGridLayout(self.offerGroupBox)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.offerMktComboBox = QtGui.QComboBox(self.offerGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offerMktComboBox.sizePolicy().hasHeightForWidth())
        self.offerMktComboBox.setSizePolicy(sizePolicy)
        self.offerMktComboBox.setObjectName(_fromUtf8("offerMktComboBox"))
        self.horizontalLayout_6.addWidget(self.offerMktComboBox)
        self.offerSearchLineEdit = QtGui.QLineEdit(self.offerGroupBox)
        self.offerSearchLineEdit.setText(_fromUtf8(""))
        self.offerSearchLineEdit.setObjectName(_fromUtf8("offerSearchLineEdit"))
        self.horizontalLayout_6.addWidget(self.offerSearchLineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.offerTableWidget = QtGui.QTableWidget(self.offerGroupBox)
        self.offerTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.offerTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.offerTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.offerTableWidget.setObjectName(_fromUtf8("offerTableWidget"))
        self.offerTableWidget.setColumnCount(4)
        self.offerTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.offerTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.offerTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.offerTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.offerTableWidget.setHorizontalHeaderItem(3, item)
        self.offerTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.offerTableWidget.horizontalHeader().setStretchLastSection(True)
        self.offerTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.offerTableWidget)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.offerOrderButton = QtGui.QPushButton(self.offerGroupBox)
        self.offerOrderButton.setObjectName(_fromUtf8("offerOrderButton"))
        self.horizontalLayout_7.addWidget(self.offerOrderButton)
        self.offerViewButton = QtGui.QPushButton(self.offerGroupBox)
        self.offerViewButton.setObjectName(_fromUtf8("offerViewButton"))
        self.horizontalLayout_7.addWidget(self.offerViewButton)
        self.offerFilterButton = QtGui.QPushButton(self.offerGroupBox)
        self.offerFilterButton.setObjectName(_fromUtf8("offerFilterButton"))
        self.horizontalLayout_7.addWidget(self.offerFilterButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.gridLayout_11.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.offerGroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.offerTab, _fromUtf8(""))
        self.orderTab = QtGui.QWidget()
        self.orderTab.setObjectName(_fromUtf8("orderTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.orderTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.orderGroupBox = QtGui.QGroupBox(self.orderTab)
        self.orderGroupBox.setObjectName(_fromUtf8("orderGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.orderGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.orderTableWidget = QtGui.QTableWidget(self.orderGroupBox)
        self.orderTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.orderTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.orderTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.orderTableWidget.setObjectName(_fromUtf8("orderTableWidget"))
        self.orderTableWidget.setColumnCount(5)
        self.orderTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.orderTableWidget.setHorizontalHeaderItem(4, item)
        self.orderTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.orderTableWidget.horizontalHeader().setStretchLastSection(True)
        self.orderTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.orderTableWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.orderProcessButton = QtGui.QPushButton(self.orderGroupBox)
        self.orderProcessButton.setObjectName(_fromUtf8("orderProcessButton"))
        self.horizontalLayout_2.addWidget(self.orderProcessButton)
        self.orderViewButton = QtGui.QPushButton(self.orderGroupBox)
        self.orderViewButton.setObjectName(_fromUtf8("orderViewButton"))
        self.horizontalLayout_2.addWidget(self.orderViewButton)
        self.orderCancelButton = QtGui.QPushButton(self.orderGroupBox)
        self.orderCancelButton.setObjectName(_fromUtf8("orderCancelButton"))
        self.horizontalLayout_2.addWidget(self.orderCancelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.orderGroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.orderTab, _fromUtf8(""))
        self.identTab = QtGui.QWidget()
        self.identTab.setObjectName(_fromUtf8("identTab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.identTab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.identMyidGroupBox = QtGui.QGroupBox(self.identTab)
        self.identMyidGroupBox.setObjectName(_fromUtf8("identMyidGroupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.identMyidGroupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.identMyidLabel = QtGui.QLabel(self.identMyidGroupBox)
        self.identMyidLabel.setObjectName(_fromUtf8("identMyidLabel"))
        self.verticalLayout_5.addWidget(self.identMyidLabel)
        self.identBtcaddrLabel = QtGui.QLabel(self.identMyidGroupBox)
        self.identBtcaddrLabel.setObjectName(_fromUtf8("identBtcaddrLabel"))
        self.verticalLayout_5.addWidget(self.identBtcaddrLabel)
        self.identBmaddrLabel = QtGui.QLabel(self.identMyidGroupBox)
        self.identBmaddrLabel.setObjectName(_fromUtf8("identBmaddrLabel"))
        self.verticalLayout_5.addWidget(self.identBmaddrLabel)
        self.gridLayout_9.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.identMyidGroupBox)
        self.identGroupBox = QtGui.QGroupBox(self.identTab)
        self.identGroupBox.setObjectName(_fromUtf8("identGroupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.identGroupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.identMktComboBox = QtGui.QComboBox(self.identGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.identMktComboBox.sizePolicy().hasHeightForWidth())
        self.identMktComboBox.setSizePolicy(sizePolicy)
        self.identMktComboBox.setObjectName(_fromUtf8("identMktComboBox"))
        self.horizontalLayout_5.addWidget(self.identMktComboBox)
        self.identSearchLineEdit = QtGui.QLineEdit(self.identGroupBox)
        self.identSearchLineEdit.setText(_fromUtf8(""))
        self.identSearchLineEdit.setObjectName(_fromUtf8("identSearchLineEdit"))
        self.horizontalLayout_5.addWidget(self.identSearchLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.identTableWidget = QtGui.QTableWidget(self.identGroupBox)
        self.identTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.identTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.identTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.identTableWidget.setObjectName(_fromUtf8("identTableWidget"))
        self.identTableWidget.setColumnCount(3)
        self.identTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.identTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.identTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.identTableWidget.setHorizontalHeaderItem(2, item)
        self.identTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.identTableWidget.horizontalHeader().setStretchLastSection(True)
        self.identTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.identTableWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.identRegButton = QtGui.QPushButton(self.identGroupBox)
        self.identRegButton.setObjectName(_fromUtf8("identRegButton"))
        self.horizontalLayout_4.addWidget(self.identRegButton)
        self.identViewButton = QtGui.QPushButton(self.identGroupBox)
        self.identViewButton.setObjectName(_fromUtf8("identViewButton"))
        self.horizontalLayout_4.addWidget(self.identViewButton)
        self.identBurnButton = QtGui.QPushButton(self.identGroupBox)
        self.identBurnButton.setObjectName(_fromUtf8("identBurnButton"))
        self.horizontalLayout_4.addWidget(self.identBurnButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_8.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.identGroupBox)
        self.gridLayout_10.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.identTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionLogin = QtGui.QAction(MainWindow)
        self.actionLogin.setObjectName(_fromUtf8("actionLogin"))
        self.menuFile.addAction(self.actionLogin)
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "METAmarket-Qt", None))
        self.chanGroupBox.setTitle(_translate("MainWindow", "Channel:", None))
        self.chanTableWidget.setSortingEnabled(True)
        item = self.chanTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Subject", None))
        item = self.chanTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Message ID", None))
        self.chanSendButton.setText(_translate("MainWindow", "Send Message", None))
        self.chanViewButton.setText(_translate("MainWindow", "View Message", None))
        self.chanDeleteButton.setText(_translate("MainWindow", "Delete Message", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chanTab), _translate("MainWindow", "Channel", None))
        self.marketGroupBox.setTitle(_translate("MainWindow", "Available Markets:", None))
        self.marketTableWidget.setSortingEnabled(True)
        item = self.marketTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.marketTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Description", None))
        self.marketImportButton.setText(_translate("MainWindow", "Import Market", None))
        self.marketViewButton.setText(_translate("MainWindow", "View Market", None))
        self.marketDeleteButton.setText(_translate("MainWindow", "Delete Market", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.marketTab), _translate("MainWindow", "Markets", None))
        self.offerGroupBox.setTitle(_translate("MainWindow", "Available Offers:", None))
        self.offerSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.offerTableWidget.setSortingEnabled(True)
        item = self.offerTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.offerTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Locale", None))
        item = self.offerTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount", None))
        item = self.offerTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price", None))
        self.offerOrderButton.setText(_translate("MainWindow", "Order", None))
        self.offerViewButton.setText(_translate("MainWindow", "View Offer", None))
        self.offerFilterButton.setText(_translate("MainWindow", "Filter Offers", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.offerTab), _translate("MainWindow", "Offers", None))
        self.orderGroupBox.setTitle(_translate("MainWindow", "My Orders:", None))
        self.orderTableWidget.setSortingEnabled(True)
        item = self.orderTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.orderTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.orderTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Locale", None))
        item = self.orderTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Amount", None))
        item = self.orderTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Price", None))
        self.orderProcessButton.setText(_translate("MainWindow", "Process", None))
        self.orderViewButton.setText(_translate("MainWindow", "View Offer", None))
        self.orderCancelButton.setText(_translate("MainWindow", "Cancel Order", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.orderTab), _translate("MainWindow", "Orders", None))
        self.identMyidGroupBox.setTitle(_translate("MainWindow", "My Identity:", None))
        self.identMyidLabel.setText(_translate("MainWindow", "ID Hash: ", None))
        self.identBtcaddrLabel.setText(_translate("MainWindow", "BTC Address: ", None))
        self.identBmaddrLabel.setText(_translate("MainWindow", "BM Address: ", None))
        self.identGroupBox.setTitle(_translate("MainWindow", "Known Identities:", None))
        self.identSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.identTableWidget.setSortingEnabled(True)
        item = self.identTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.identTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Rep Score", None))
        item = self.identTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID", None))
        self.identRegButton.setText(_translate("MainWindow", "Register My Identity", None))
        self.identViewButton.setText(_translate("MainWindow", "View Identity", None))
        self.identBurnButton.setText(_translate("MainWindow", "BURN BTC", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.identTab), _translate("MainWindow", "Identities", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionLogin.setText(_translate("MainWindow", "Login", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

